/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgRouteImport } from './routes/og'
import { Route as PostsRouteImport } from './routes/_posts'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppResumeRouteImport } from './routes/_app/resume'
import { Route as PostsPostsIndexRouteImport } from './routes/_posts/posts/index'
import { Route as PostsPostsSlugRouteImport } from './routes/_posts/posts/$slug'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/_posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const PostsPostsIndexRoute = PostsPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => PostsRoute,
} as any)
const PostsPostsSlugRoute = PostsPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => PostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/og': typeof OgRoute
  '/resume': typeof AppResumeRoute
  '/': typeof AppIndexRoute
  '/posts/$slug': typeof PostsPostsSlugRoute
  '/posts': typeof PostsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/og': typeof OgRoute
  '/resume': typeof AppResumeRoute
  '/': typeof AppIndexRoute
  '/posts/$slug': typeof PostsPostsSlugRoute
  '/posts': typeof PostsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_posts': typeof PostsRouteWithChildren
  '/og': typeof OgRoute
  '/_app/resume': typeof AppResumeRoute
  '/_app/': typeof AppIndexRoute
  '/_posts/posts/$slug': typeof PostsPostsSlugRoute
  '/_posts/posts/': typeof PostsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/og' | '/resume' | '/' | '/posts/$slug' | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to: '/og' | '/resume' | '/' | '/posts/$slug' | '/posts'
  id:
    | '__root__'
    | '/_app'
    | '/_posts'
    | '/og'
    | '/_app/resume'
    | '/_app/'
    | '/_posts/posts/$slug'
    | '/_posts/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  OgRoute: typeof OgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_posts': {
      id: '/_posts'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume': {
      id: '/_app/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_posts/posts/': {
      id: '/_posts/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsPostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/_posts/posts/$slug': {
      id: '/_posts/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsPostsSlugRouteImport
      parentRoute: typeof PostsRoute
    }
  }
}

interface AppRouteChildren {
  AppResumeRoute: typeof AppResumeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppResumeRoute: AppResumeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PostsRouteChildren {
  PostsPostsSlugRoute: typeof PostsPostsSlugRoute
  PostsPostsIndexRoute: typeof PostsPostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostsSlugRoute: PostsPostsSlugRoute,
  PostsPostsIndexRoute: PostsPostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  OgRoute: OgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
